### ISSUE TITLE
Take 2nd course "Introduction to Tidyverse"

### ISSUE THREAD

**Issue by lcchapman** [nvs-group/R_Training#3]
https://www.datacamp.com/courses/introduction-to-the-tidyverse

2nd course for all team members.

**Comment by chapmjs** [comment]
Here is a "cheatsheet" for the second course on Tidyverse:
[https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Tidyverse+Cheat+Sheet.pdf](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Tidyverse+Cheat+Sheet.pdf)
